a = int(input("Enter first number(a):"))
b = int(input("Enter first number(b):"))
c = int(input("Enter first number(c):"))
print("a =", a, "b =", b, "c =", c, "\n")
print(f"Is a equal to c?{a==c}")
print(f"Is a less than b?{a<b}")
print(f"Is b greater than or equal to a?{b>=a}")
print(f"Is a not equal to b? {a!=b}")
print(f"Are both a < b AND b > c true?{a<b and b>c}")
print(f"Is at least one true: a > b OR a == c?{a>b or a==c}")
print(f"Is it NOT true that a equals b?{not a== b}\n")
first_word = input("Enter first word:")
second_word = input("Enter second word:")
print("word1 =", first_word, "," "word2 =", second_word, "\n")
print(f"Are the strings equal?{first_word==second_word}")
print(f"Are the strings equal (lowercase)?{first_word.lower()==second_word.lower()}")
print(f"Length of word1:{len(first_word)}")
